title: Evan Pratten
description: >- # this means to ignore newlines until "baseurl:"
  A site where I share my programming work, thoughts, and misadventures
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://retrylife.ca" # the base hostname & protocol for your site, e.g. http://example.com

about: >-
  I am an 18 year old programming student. I enjoy learning new concepts, 
  building projects out of random ideas and obscure technologies, and working with new tools. 
  My projects range from building tools to help me with school work, and robotics, to radios 
  and video production.

permalink: /blog/:year/:month/:day/:slug

ga_analytics: G-7GDG18PD12

# Social
twitter_username: ewpratten
insta_username: evanpratten
github_username:  ewpratten
devrant_username: ewpratten
gitlab_username: ewpratten
rtlgit_username: ewpratten
keybase_username: ewpratten

# Payments
paypal_username: ewpratten
btc_address: 17H1ad7t1h5bFcxhyL8naZJhY5E2iiW7yk
stellar_address: GBBUKCQQULS3TLGPKLHIFN2YZUAOTCZHW7ON7CFFJIY5QPFBWGYVA2YQ

# Build settings
markdown: kramdown
kramdown:
  # input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

collections:
  papers:
    output: true
  drafts:
    output: true
  notes:
    output: true
  music:
    output: true
    order:
      - retroactive.md
      - spamcalls.md
      - imagined.md

feed:
  tags: true
  posts_limit: 200

highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

plugins:
  - jekyll-feed
  - jekyll-redirect-from # https://github.com/jekyll/jekyll-redirect-from
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-avatar

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .devcontainer/
  - .vscode/
  - README.md
  - package-lock.json
  - CNAME
  - .gitignore
